import * as Dialog from '@radix-ui/react-dialog';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Building2, FilePlus2, Mail, MapPin, MessageCircle, Pencil, Phone, Plus, Search, Trash2, X } from 'lucide-react';
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { api, jsonBody, pageResult } from '../lib/api';
import type { Customer, PageResult } from '../types';
import { useToast } from '../context/ToastContext';
import { Button, EmptyState, ErrorState, Field, LoadingState, PageHeader, Pagination } from '../components/ui';
import { ConfirmDialog } from '../components/ConfirmDialog';

const blank = { name: '', phone: '', whatsapp: '', email: '', city: '', projectType: 'residential', serviceInterest: 'solar', address: '', notes: '' };
const rowId = (row: Customer) => row.id || row._id || '';

export default function Customers() {
  const [page, setPage] = useState(1); const [search, setSearch] = useState(''); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<Customer | null>(null); const [deleting, setDeleting] = useState<Customer | null>(null); const [form, setForm] = useState(blank);
  const { notify } = useToast(); const client = useQueryClient();
  const query = useQuery({ queryKey: ['customers', page, search], queryFn: () => api<PageResult<Customer> | Customer[]>(`/customers?page=${page}&limit=20${search ? `&search=${encodeURIComponent(search)}` : ''}`) });
  const data = query.data ? pageResult(query.data) : null;
  const save = useMutation({ mutationFn: () => api<Customer>(editing ? `/customers/${rowId(editing)}` : '/customers', { method: editing ? 'PUT' : 'POST', ...jsonBody(form) }), onSuccess: () => { client.invalidateQueries({ queryKey: ['customers'] }); setOpen(false); notify(editing ? 'Customer updated' : 'Customer added', 'success'); }, onError: error => notify(error.message, 'error') });
  const remove = useMutation({ mutationFn: () => api(`/customers/${rowId(deleting!)}`, { method: 'DELETE' }), onSuccess: () => { client.invalidateQueries({ queryKey: ['customers'] }); setDeleting(null); notify('Customer deleted', 'success'); }, onError: error => notify(error.message, 'error') });
  function edit(row?: Customer) { setEditing(row || null); setForm(row ? { ...blank, ...row } : blank); setOpen(true); }
  const whatsapp = (row: Customer) => `https://wa.me/${String(row.whatsapp || row.phone).replace(/\D/g, '').replace(/^0/, '92')}`;
  return <div className="page"><PageHeader title="Customers" description="Customer profiles, project interests, and quotation activity." actions={<Button onClick={() => edit()}><Plus/>Add customer</Button>}/><div className="toolbar"><div className="search-box"><Search/><input value={search} onChange={event => { setSearch(event.target.value); setPage(1); }} placeholder="Search name, phone, email or city…" aria-label="Search customers"/></div></div>
    {query.isLoading ? <LoadingState label="Loading customers"/> : query.error ? <ErrorState error={query.error} retry={() => query.refetch()}/> : !data?.items.length ? <EmptyState title="No customers found" message="Add a customer to start building a quotation." action={<Button onClick={() => edit()}><Plus/>Add customer</Button>}/> : <><div className="responsive-table customer-table"><div className="table-head"><span>Customer</span><span>Contact</span><span>Project</span><span>Location</span><span>Actions</span></div>{data.items.map(row => <article className="table-row" key={rowId(row)}><div className="customer-cell"><span className="avatar avatar--square"><Building2/></span><span><strong>{row.name}</strong><small>{row.email || 'No email added'}</small></span></div><div className="stack-cell"><span><Phone/> {row.phone}</span>{row.whatsapp && <span><MessageCircle/> {row.whatsapp}</span>}</div><div><strong className="mobile-label">Project</strong><span className="table-pill">{row.projectType || 'Residential'}</span><small>{row.serviceInterest || 'Solar'}</small></div><div className="stack-cell"><span><MapPin/> {row.city}</span><small>{row.address || 'Address not added'}</small></div><div className="row-actions row-actions--labeled"><a href={whatsapp(row)} target="_blank" rel="noreferrer" aria-label={`WhatsApp ${row.name}`}><MessageCircle/><span>WhatsApp</span></a><Link to={`/quotation-builder?customer=${rowId(row)}`} aria-label={`New quotation for ${row.name}`}><FilePlus2/><span>Quote</span></Link><button onClick={() => edit(row)} aria-label={`Edit ${row.name}`}><Pencil/><span>Edit</span></button><button className="danger" onClick={() => setDeleting(row)} aria-label={`Delete ${row.name}`}><Trash2/><span>Delete</span></button></div></article>)}</div><Pagination page={data.meta.page} pages={data.meta.pages} onChange={setPage}/></>}
    <Dialog.Root open={open} onOpenChange={setOpen}><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className="dialog dialog--form"><div className="dialog__header"><div><Dialog.Title>{editing ? 'Edit customer' : 'Add customer'}</Dialog.Title><Dialog.Description>Store the information needed for proposals and follow-ups.</Dialog.Description></div><Dialog.Close className="dialog__close" aria-label="Close"><X/></Dialog.Close></div><form className="form-grid" onSubmit={event => { event.preventDefault(); save.mutate(); }}>{Object.entries({ name: 'Customer or company name', phone: 'Phone', whatsapp: 'WhatsApp', email: 'Email', city: 'City', address: 'Site address' }).map(([name,label]) => <Field key={name} label={label}><input className="input" type={name === 'email' ? 'email' : 'text'} value={form[name as keyof typeof form]} required={['name','phone','city'].includes(name)} onChange={event => setForm(value => ({ ...value, [name]: event.target.value }))}/></Field>)}<Field label="Project type"><select className="select" value={form.projectType} onChange={event => setForm(value => ({ ...value, projectType: event.target.value }))}><option value="residential">Residential</option><option value="commercial">Commercial</option><option value="industrial">Industrial</option><option value="agriculture">Agriculture</option></select></Field><Field label="Service interest"><select className="select" value={form.serviceInterest} onChange={event => setForm(value => ({ ...value, serviceInterest: event.target.value }))}><option value="solar">Solar</option><option value="battery-storage">Battery storage</option><option value="energy-audit">Energy audit</option><option value="operations-maintenance">Operations & maintenance</option></select></Field><Field label="Notes"><textarea className="textarea" value={form.notes} onChange={event => setForm(value => ({ ...value, notes: event.target.value }))}/></Field><div className="contact-preview"><Mail/><span>Email is used when sending quotations.</span></div><div className="form-grid__full dialog__actions"><Button tone="secondary" type="button" onClick={() => setOpen(false)}>Cancel</Button><Button disabled={save.isPending}>{save.isPending ? 'Saving…' : 'Save customer'}</Button></div></form></Dialog.Content></Dialog.Portal></Dialog.Root>
    <ConfirmDialog open={Boolean(deleting)} title="Delete customer?" message="Customers linked to quotations cannot be deleted, preserving your sales history." confirmLabel="Delete customer" busy={remove.isPending} onCancel={() => setDeleting(null)} onConfirm={() => remove.mutate()}/>
  </div>;
}
