import * as Dialog from '@radix-ui/react-dialog';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Camera, CheckCircle2, KeyRound, Laptop, LockKeyhole, LogOut, QrCode, ShieldCheck, Smartphone, Upload, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import { api, jsonBody } from '../lib/api';
import type { User } from '../types';
import { fullName, shortDate, titleCase } from '../lib/format';
import { useAuth } from '../context/AuthContext';
import { useToast } from '../context/ToastContext';
import { Badge, Button, Card, ErrorState, Field, LoadingState, PageHeader } from '../components/ui';

interface Session { id:string; createdAt:string; lastSeenAt:string; ip:string; userAgent:string; current:boolean }
export default function Profile(){
  const {user,refresh}=useAuth();const {notify}=useToast();const client=useQueryClient();const [form,setForm]=useState<Record<string,string>>({});const [mfa,setMfa]=useState<{secret:string;qrCode:string}|null>(null);const [mfaCode,setMfaCode]=useState('');
  useEffect(()=>{if(user)setForm(Object.fromEntries(['firstName','lastName','phone','alternatePhone','dateOfBirth','gender','city','employeeId','address','department','designation','emergencyContactName','emergencyContactPhone','profilePicture'].map(key=>[key,String((user as unknown as Record<string,unknown>)[key]||'').slice(0,key==='dateOfBirth'?10:undefined)])));},[user]);
  const sessions=useQuery({queryKey:['sessions'],queryFn:()=>api<Session[]>('/auth/sessions')});
  const save=useMutation({mutationFn:()=>api<{user:User}>('/auth/profile',{method:'PATCH',...jsonBody(form)}),onSuccess:async()=>{await refresh();notify('Profile updated','success');},onError:error=>notify(error.message,'error')});
  const password=useMutation({mutationFn:(body:unknown)=>api('/auth/change-password',{method:'POST',...jsonBody(body)}),onSuccess:()=>notify('Password changed and other sessions revoked','success'),onError:error=>notify(error.message,'error')});
  const revoke=useMutation({mutationFn:(id:string)=>api(`/auth/sessions/${id}`,{method:'DELETE'}),onSuccess:()=>{client.invalidateQueries({queryKey:['sessions']});notify('Session revoked','success');},onError:error=>notify(error.message,'error')});
  async function upload(file?:File){if(!file)return;try{const body=new FormData();body.append('image',file);body.append('folder','profiles');const result=await api<{url:string}>('/uploads/image',{method:'POST',body,timeout:30000});setForm(value=>({...value,profilePicture:result.url}));notify('Picture ready. Save profile to apply it.','success');}catch(error){notify(error instanceof Error?error.message:'Upload failed','error');}}
  async function setupMfa(){try{setMfa(await api('/auth/mfa/setup',{method:'POST'}));}catch(error){notify(error instanceof Error?error.message:'MFA setup failed','error');}}
  async function verifyMfa(){try{await api('/auth/mfa/verify',{method:'POST',...jsonBody({code:mfaCode})});setMfa(null);await refresh();notify('Multi-factor authentication enabled','success');}catch(error){notify(error instanceof Error?error.message:'Invalid code','error');}}
  if(!user)return null;
  return <div className="page"><PageHeader title="My Account" description="Profile, contact information, security, and signed-in devices."/><div className="profile-layout"><div className="profile-main"><Card className="settings-card"><div className="section-heading"><div><span className="eyebrow">Personal details</span><h2>Profile information</h2><p>Keep your contact and employment information current.</p></div></div><div className="profile-picture"><div className="avatar avatar--large">{form.profilePicture?<img src={form.profilePicture} alt="Profile preview"/>:user.firstName[0]}</div><label><Camera/><span>Change picture</span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>upload(event.target.files?.[0])}/></label><small>JPEG, PNG or WebP up to 5 MB.</small></div><form className="form-grid" onSubmit={event=>{event.preventDefault();save.mutate();}}>{Object.entries({firstName:'First name',lastName:'Last name',phone:'Phone',alternatePhone:'Alternate phone',dateOfBirth:'Date of birth',city:'City',employeeId:'Employee ID',address:'Address',department:'Department',designation:'Designation',emergencyContactName:'Emergency contact',emergencyContactPhone:'Emergency phone'}).map(([key,label])=><Field key={key} label={label}><input className="input" type={key==='dateOfBirth'?'date':'text'} value={form[key]||''} required={!['alternatePhone','employeeId'].includes(key)} onChange={event=>setForm(value=>({...value,[key]:event.target.value}))}/></Field>)}<Field label="Gender"><select className="select" value={form.gender||'prefer_not_to_say'} onChange={event=>setForm(value=>({...value,gender:event.target.value}))}><option value="prefer_not_to_say">Prefer not to say</option><option value="male">Male</option><option value="female">Female</option><option value="other">Other</option></select></Field><Field label="Email"><input className="input" value={user.email} disabled/></Field><div className="form-grid__full"><Button disabled={save.isPending}>{save.isPending?'Saving…':'Save profile'}</Button></div></form></Card>
    <Card className="settings-card"><div className="section-heading"><div><span className="eyebrow">Credentials</span><h2>Change password</h2><p>Changing your password signs out every other device.</p></div><LockKeyhole/></div><form className="form-grid" onSubmit={event=>{event.preventDefault();const data=new FormData(event.currentTarget);if(data.get('newPassword')!==data.get('confirmPassword'))return notify('New passwords do not match','error');password.mutate({currentPassword:data.get('currentPassword'),newPassword:data.get('newPassword')});event.currentTarget.reset();}}><Field label="Current password"><input className="input" name="currentPassword" type="password" autoComplete="current-password" required/></Field><Field label="New password"><input className="input" name="newPassword" type="password" autoComplete="new-password" minLength={10} required/></Field><Field label="Confirm new password"><input className="input" name="confirmPassword" type="password" autoComplete="new-password" minLength={10} required/></Field><div className="password-requirement"><KeyRound/>At least 10 characters with uppercase, lowercase, and a number.</div><div className="form-grid__full"><Button disabled={password.isPending}>Change password</Button></div></form></Card></div>
    <aside className="profile-side"><Card className="account-card"><div className="avatar avatar--large">{user.profilePicture?<img src={user.profilePicture} alt=""/>:user.firstName[0]}</div><h2>{fullName(user)}</h2><span>{user.designation||titleCase(user.role)}</span><Badge tone={user.status==='active'?'success':'warning'}>{titleCase(user.status)}</Badge><dl><div><dt>Role</dt><dd>{titleCase(user.role)}</dd></div><div><dt>Last login</dt><dd>{shortDate(user.lastLoginAt)}</dd></div><div><dt>Security</dt><dd>{user.mfaEnabled?'MFA enabled':'Password only'}</dd></div></dl></Card>
      <Card className="settings-card compact-card"><div className="section-heading"><div><span className="eyebrow">Extra protection</span><h2>Multi-factor authentication</h2></div><ShieldCheck/></div>{user.mfaEnabled?<div className="success-empty"><CheckCircle2/><span><strong>MFA is enabled</strong><small>Your authenticator is required at sign in.</small></span></div>:<><p className="muted">Add a six-digit authenticator code to protect your account.</p><Button tone="secondary" onClick={setupMfa}><QrCode/>Set up MFA</Button></>}</Card>
      <Card className="settings-card compact-card"><div className="section-heading"><div><span className="eyebrow">Security</span><h2>Active sessions</h2></div><Laptop/></div>{sessions.isLoading?<LoadingState label="Loading sessions"/>:sessions.error?<ErrorState error={sessions.error}/>:sessions.data?.map(session=><div className="session-row" key={session.id}>{/mobile|android|iphone/i.test(session.userAgent)?<Smartphone/>:<Laptop/>}<span><strong>{session.current?'This device':'Signed-in device'}</strong><small>{session.ip||'Private network'} · {shortDate(session.lastSeenAt)}</small></span>{session.current?<Badge tone="success">Current</Badge>:<button onClick={()=>revoke.mutate(session.id)} aria-label="Sign out device"><LogOut/></button>}</div>)}</Card></aside></div>
    <Dialog.Root open={Boolean(mfa)} onOpenChange={open=>!open&&setMfa(null)}><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className="dialog dialog--small"><div className="dialog__header"><div><Dialog.Title>Set up authenticator</Dialog.Title><Dialog.Description>Scan this QR code, then enter the six-digit code.</Dialog.Description></div><Dialog.Close className="dialog__close"><X/></Dialog.Close></div>{mfa&&<div className="mfa-setup"><img src={mfa.qrCode} alt="Authenticator QR code"/><code>{mfa.secret}</code><Field label="Authentication code"><input className="input" value={mfaCode} onChange={event=>setMfaCode(event.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric" autoFocus/></Field><Button disabled={mfaCode.length!==6} onClick={verifyMfa}><ShieldCheck/>Enable MFA</Button></div>}</Dialog.Content></Dialog.Portal></Dialog.Root>
  </div>;
}
