import * as Dialog from '@radix-ui/react-dialog';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { CheckCircle2, Copy, Download, Eye, FilePlus2, FileText, Mail, MessageCircle, MoreHorizontal, Pencil, Search, Send, Trash2, X } from 'lucide-react';
import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { api, jsonBody, pageResult } from '../lib/api';
import type { Customer, PageResult, Quotation, QuoteStatus } from '../types';
import { money, shortDate, titleCase } from '../lib/format';
import { useAuth } from '../context/AuthContext';
import { useToast } from '../context/ToastContext';
import { Badge, Button, EmptyState, ErrorState, Field, LoadingState, PageHeader, Pagination } from '../components/ui';
import { ConfirmDialog } from '../components/ConfirmDialog';

const statusTone = (status: string) => status === 'accepted' || status === 'approved' ? 'success' : status === 'rejected' || status === 'cancelled' ? 'danger' : status === 'pending_approval' || status === 'expired' ? 'warning' : 'info';
const rowId = (row: Quotation) => row.id || row._id || '';

export default function Quotations() {
  const [page, setPage] = useState(1); const [search, setSearch] = useState(''); const [status, setStatus] = useState('all'); const [deleting, setDeleting] = useState<Quotation | null>(null); const [statusRow, setStatusRow] = useState<Quotation | null>(null); const [pdfRow, setPdfRow] = useState<Quotation | null>(null); const [nextStatus, setNextStatus] = useState<QuoteStatus>('sent');
  const client = useQueryClient(); const { notify } = useToast(); const { hasPermission } = useAuth();
  const params = new URLSearchParams({ page: String(page), limit: '20', ...(search ? { search } : {}), ...(status !== 'all' ? { status } : {}) });
  const query = useQuery({ queryKey: ['quotations', page, search, status], queryFn: () => api<PageResult<Quotation> | Quotation[]>(`/quotations?${params}`) });
  const customers = useQuery({ queryKey: ['customers','quote-map'], queryFn: () => api<Customer[]>('/customers') });
  const customerMap = useMemo(() => new Map((customers.data || []).map(row => [row.id || row._id, row])), [customers.data]); const data = query.data ? pageResult(query.data) : null;
  const remove = useMutation({ mutationFn: () => api(`/quotations/${rowId(deleting!)}`, { method: 'DELETE' }), onSuccess: () => { client.invalidateQueries({ queryKey: ['quotations'] }); setDeleting(null); notify('Quotation deleted', 'success'); }, onError: error => notify(error.message, 'error') });
  const duplicate = useMutation({ mutationFn: (row: Quotation) => api<Quotation>(`/quotations/${rowId(row)}/duplicate`, { method: 'POST', ...jsonBody({}) }), onSuccess: result => { client.invalidateQueries({ queryKey: ['quotations'] }); notify(`Created ${result.quotationNumber}`, 'success'); }, onError: error => notify(error.message, 'error') });
  const updateStatus = useMutation({ mutationFn: () => api(`/quotations/${rowId(statusRow!)}/status`, { method: 'PATCH', ...jsonBody({ status: nextStatus }) }), onSuccess: () => { client.invalidateQueries({ queryKey: ['quotations'] }); setStatusRow(null); notify('Quotation status updated', 'success'); }, onError: error => notify(error.message, 'error') });
  const email = useMutation({ mutationFn: (row: Quotation) => api('/email/send-quotation', { method: 'POST', ...jsonBody({ quotationId: rowId(row) }), timeout: 20_000 }), onSuccess: () => { client.invalidateQueries({ queryKey: ['quotations'] }); notify('Quotation email sent', 'success'); }, onError: error => notify(error.message, 'error') });
  async function downloadPdf() { const element = document.getElementById('react-quote-preview'); if (!element || !pdfRow) return; const { generateQuotationPDF } = await import('../../utils/pdf-generator.js'); await generateQuotationPDF(element, pdfRow.quotationNumber); }
  const statuses = ['all','draft','pending_approval','approved','sent','viewed','accepted','rejected','expired','cancelled'];
  return <div className="page"><PageHeader title="Quotations" description="Track proposals, approvals, revisions, follow-ups, and outcomes." actions={<div className="page-action-group">{hasPermission('exports_manage') && <a className="button button--secondary button--md" href="/api/quotations/export/csv"><Download/>Export</a>}<Link to="/quotation-builder"><Button><FilePlus2/>New quotation</Button></Link></div>}/>
    <div className="toolbar"><div className="search-box"><Search/><input value={search} onChange={event => { setSearch(event.target.value); setPage(1); }} placeholder="Search quotation reference…" aria-label="Search quotations"/></div></div><div className="chip-scroll" role="tablist" aria-label="Quotation status">{statuses.map(item => <button key={item} role="tab" aria-selected={status === item} className={status === item ? 'active' : ''} onClick={() => { setStatus(item); setPage(1); }}>{titleCase(item)}</button>)}</div>
    {query.isLoading ? <LoadingState label="Loading quotations"/> : query.error ? <ErrorState error={query.error} retry={() => query.refetch()}/> : !data?.items.length ? <EmptyState title="No quotations found" message="Create a proposal or change the selected filters." action={<Link to="/quotation-builder"><Button><FilePlus2/>New quotation</Button></Link>}/> : <><div className="responsive-table quote-table"><div className="table-head"><span>Quotation</span><span>Customer</span><span>System</span><span>Total</span><span>Status</span><span>Actions</span></div>{data.items.map(row => { const customer = customerMap.get(row.customerId); return <article className="table-row" key={rowId(row)}><div className="customer-cell"><span className="record-icon"><FileText/></span><span><strong>{row.quotationNumber}</strong><small>Revision {row.revision || 1} · {shortDate(row.createdAt)}</small></span></div><div><strong className="mobile-label">Customer</strong><span>{customer?.name || 'Customer record'}</span><small>{customer?.city || ''}</small></div><div><strong className="mobile-label">System</strong><span>{row.systemSize} kW</span><small>{titleCase(row.systemType)}</small></div><div><strong className="mobile-label">Total</strong><strong>{money(row.grandTotal)}</strong></div><div><strong className="mobile-label">Status</strong><Badge tone={statusTone(row.status)}>{titleCase(row.status)}</Badge>{row.followUpAt && <small>Follow up {shortDate(row.followUpAt)}</small>}</div><div className="row-actions"><Link to={`/quotation-builder/${rowId(row)}`} aria-label={`Edit ${row.quotationNumber}`}><Pencil/></Link><button onClick={() => duplicate.mutate(row)} aria-label={`Duplicate ${row.quotationNumber}`}><Copy/></button><button onClick={() => { setStatusRow(row); setNextStatus(row.status === 'draft' ? 'sent' : 'accepted'); }} aria-label={`Update ${row.quotationNumber} status`}><CheckCircle2/></button><button onClick={() => setPdfRow(row)} aria-label={`Preview PDF for ${row.quotationNumber}`}><Eye/></button>{customer?.email && <button onClick={() => email.mutate(row)} disabled={email.isPending} aria-label={`Email ${row.quotationNumber}`}><Mail/></button>}{customer?.whatsapp || customer?.phone ? <a target="_blank" rel="noreferrer" href={`https://wa.me/${String(customer.whatsapp || customer.phone).replace(/\D/g,'').replace(/^0/,'92')}`} aria-label={`Share ${row.quotationNumber} on WhatsApp`}><MessageCircle/></a> : null}<button className="danger" onClick={() => setDeleting(row)} aria-label={`Delete ${row.quotationNumber}`}><Trash2/></button></div></article>; })}</div><Pagination page={data.meta.page} pages={data.meta.pages} onChange={setPage}/></>}
    <Dialog.Root open={Boolean(statusRow)} onOpenChange={open => !open && setStatusRow(null)}><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className="dialog dialog--small"><div className="dialog__header"><div><Dialog.Title>Update quotation status</Dialog.Title><Dialog.Description>{statusRow?.quotationNumber}</Dialog.Description></div><Dialog.Close className="dialog__close"><X/></Dialog.Close></div><div className="form-stack"><Field label="New status"><select className="select" value={nextStatus} onChange={event => setNextStatus(event.target.value as QuoteStatus)}>{statuses.slice(1).map(item => <option key={item} value={item}>{titleCase(item)}</option>)}</select></Field><div className="dialog__actions"><Button tone="secondary" onClick={() => setStatusRow(null)}>Cancel</Button><Button onClick={() => updateStatus.mutate()} disabled={updateStatus.isPending}><Send/>Update status</Button></div></div></Dialog.Content></Dialog.Portal></Dialog.Root>
    <Dialog.Root open={Boolean(pdfRow)} onOpenChange={open => !open && setPdfRow(null)}><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className="dialog dialog--preview"><div className="dialog__header"><div><Dialog.Title>Quotation preview</Dialog.Title><Dialog.Description>Review the commercial snapshot before download.</Dialog.Description></div><Dialog.Close className="dialog__close" aria-label="Close preview"><X/></Dialog.Close></div>{pdfRow && <section id="react-quote-preview" className="pdf-preview"><header><div><strong>SKYLAND ENERGY</strong><small>Your Energy Management Company</small></div><span>QUOTATION</span></header><div className="pdf-meta"><span><small>Reference</small><strong>{pdfRow.quotationNumber}</strong></span><span><small>Customer</small><strong>{customerMap.get(pdfRow.customerId)?.name || 'Customer'}</strong></span><span><small>System</small><strong>{pdfRow.systemSize} kW {titleCase(pdfRow.systemType)}</strong></span><span><small>Status</small><strong>{titleCase(pdfRow.status)}</strong></span></div><table><thead><tr><th>Item</th><th>Qty</th><th>Rate</th><th>Total</th></tr></thead><tbody>{pdfRow.items.map((item,index)=><tr key={index}><td>{item.name}</td><td>{item.quantity} {item.unit}</td><td>{money(item.unitPrice)}</td><td>{money(item.quantity*item.unitPrice)}</td></tr>)}</tbody></table><div className="pdf-total"><span>Grand total</span><strong>{money(pdfRow.grandTotal)}</strong></div><footer>Skyland Energy (Pvt.) Ltd · Lahore, Pakistan · theskylandenergy.com</footer></section>}<div className="dialog__actions"><Button tone="secondary" onClick={() => setPdfRow(null)}>Close</Button><Button onClick={downloadPdf}><Download/>Download PDF</Button></div></Dialog.Content></Dialog.Portal></Dialog.Root>
    <ConfirmDialog open={Boolean(deleting)} title="Delete quotation?" message="This permanently removes the quotation and its activity history. Consider cancelling it instead." confirmLabel="Delete quotation" busy={remove.isPending} onCancel={() => setDeleting(null)} onConfirm={() => remove.mutate()}/>
  </div>;
}
