import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Bell, Building2, Database, Download, FileText, Save, ShieldCheck } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { api, jsonBody } from '../lib/api';
import { useToast } from '../context/ToastContext';
import { useAuth } from '../context/AuthContext';
import { Badge, Button, Card, ErrorState, Field, LoadingState, PageHeader } from '../components/ui';

interface SettingRow { key: string; value: unknown }
const defaults: Record<string, unknown> = { companyName: 'Skyland Energy (Pvt.) Ltd', companyAddress: '286 H-1, Johar Town, Lahore, Pakistan', companyPhone: '', companyWebsite: 'https://www.theskylandenergy.com', companyTagline: 'Your Energy Management Company', companyAccreditation: 'AEDB & PEC Approved', validityDays: 5, advancePercent: 20, exchangeRate: 285, defaultTerms: '', approvalThreshold: 1000000, followUpDays: 3, emailNotifications: true, approvalNotifications: true };

export default function Settings() {
  const { user } = useAuth(); const administrator = ['super_admin','admin'].includes(user?.role || '');
  const [section, setSection] = useState(administrator ? 'company' : 'quotation'); const [values, setValues] = useState(defaults); const [saved, setSaved] = useState(defaults); const { notify } = useToast(); const client = useQueryClient();
  const query = useQuery({ queryKey: ['settings'], queryFn: () => api<SettingRow[]>('/settings') });
  useEffect(() => { if (!query.data) return; const loaded = { ...defaults, ...Object.fromEntries(query.data.map(row => [row.key,row.value])) }; setValues(loaded); setSaved(loaded); }, [query.data]);
  const changed = useMemo(() => Object.keys(values).filter(key => JSON.stringify(values[key]) !== JSON.stringify(saved[key])), [values,saved]);
  useEffect(() => { const warn = (event: BeforeUnloadEvent) => { if (changed.length) event.preventDefault(); }; window.addEventListener('beforeunload', warn); return () => window.removeEventListener('beforeunload', warn); }, [changed.length]);
  const save = useMutation({ mutationFn: async () => { for (const key of changed) await api('/settings', { method: 'POST', ...jsonBody({ key, value: values[key] }) }); }, onSuccess: () => { setSaved(values); client.invalidateQueries({ queryKey: ['settings'] }); notify('Settings saved', 'success'); }, onError: error => notify(error.message, 'error') });
  function set(key: string, value: unknown) { setValues(current => ({ ...current, [key]: value })); }
  async function exportData() { try { const [products, customers, quotations, settings] = await Promise.all([api('/products'),api('/customers'),api('/quotations'),api('/settings')]); const blob = new Blob([JSON.stringify({ products,customers,quotations,settings,exportedAt:new Date().toISOString() },null,2)],{type:'application/json'}); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href=url; anchor.download=`skyland-export-${new Date().toISOString().slice(0,10)}.json`; anchor.click(); URL.revokeObjectURL(url); notify('Data export prepared','success'); } catch(error){ notify(error instanceof Error ? error.message : 'Export failed','error'); } }
  const nav = (administrator ? [{ id:'company',label:'Company',icon:Building2 },{ id:'quotation',label:'Quotation defaults',icon:FileText },{ id:'security',label:'Security',icon:ShieldCheck },{ id:'notifications',label:'Notifications',icon:Bell },{ id:'data',label:'Data',icon:Database }] : [{ id:'quotation',label:'Quotation defaults',icon:FileText }]);
  if (query.isLoading) return <LoadingState label="Loading settings"/>; if (query.error) return <ErrorState error={query.error} retry={() => query.refetch()}/>;
  return <div className="page"><PageHeader title="Settings" description="Company identity, quotation defaults, security, notifications, and data." actions={<Button onClick={() => save.mutate()} disabled={!changed.length || save.isPending}><Save/>{save.isPending ? 'Saving…' : 'Save changes'}</Button>}/><div className="settings-layout"><nav className="settings-nav" aria-label="Settings sections">{nav.map(({id,label,icon:Icon}) => <button key={id} className={section===id?'active':''} onClick={() => setSection(id)}><Icon/><span>{label}</span>{changed.some(key => ({company:['companyName','companyAddress','companyPhone','companyWebsite','companyTagline','companyAccreditation'],quotation:['validityDays','advancePercent','exchangeRate','defaultTerms','approvalThreshold','followUpDays'],notifications:['emailNotifications','approvalNotifications']}[id] || []).includes(key)) && <i/>}</button>)}</nav><div className="settings-content">
    {section==='company' && <Card className="settings-card"><div className="section-heading"><div><span className="eyebrow">Brand identity</span><h2>Company information</h2><p>Used in proposal headers, footers, and customer communication.</p></div></div><div className="form-grid">{Object.entries({companyName:'Company name',companyAddress:'Address',companyPhone:'Phone',companyWebsite:'Website',companyTagline:'Tagline',companyAccreditation:'Accreditation'}).map(([key,label]) => <Field key={key} label={label}><input className="input" value={String(values[key] || '')} onChange={event => set(key,event.target.value)}/></Field>)}</div></Card>}
    {section==='quotation' && <Card className="settings-card"><div className="section-heading"><div><span className="eyebrow">Proposal behavior</span><h2>Quotation defaults</h2><p>New quotations start with these commercial settings.</p></div></div><div className="form-grid"><Field label="Validity days"><input className="input" type="number" min="1" value={Number(values.validityDays)} onChange={event=>set('validityDays',Number(event.target.value))}/></Field><Field label="Advance payment (%)"><input className="input" type="number" min="0" max="100" value={Number(values.advancePercent)} onChange={event=>set('advancePercent',Number(event.target.value))}/></Field><Field label="USD exchange rate"><input className="input" type="number" min="1" value={Number(values.exchangeRate)} onChange={event=>set('exchangeRate',Number(event.target.value))}/></Field><Field label="Approval threshold (PKR)"><input className="input" type="number" min="0" value={Number(values.approvalThreshold)} onChange={event=>set('approvalThreshold',Number(event.target.value))}/></Field><Field label="Default follow-up after days"><input className="input" type="number" min="1" value={Number(values.followUpDays)} onChange={event=>set('followUpDays',Number(event.target.value))}/></Field><Field label="Default terms and conditions"><textarea className="textarea textarea--large" value={String(values.defaultTerms || '')} onChange={event=>set('defaultTerms',event.target.value)}/></Field></div></Card>}
    {section==='security' && <Card className="settings-card"><div className="section-heading"><div><span className="eyebrow">System protection</span><h2>Security policy</h2><p>Authentication safeguards are enforced by the server.</p></div><Badge tone="success">High protection</Badge></div><div className="security-list"><div><ShieldCheck/><span><strong>Revocable sessions</strong><small>Sessions are hashed in MongoDB and can be remotely revoked.</small></span></div><div><ShieldCheck/><span><strong>CSRF and strict origin protection</strong><small>State-changing browser requests require a matching security token.</small></span></div><div><ShieldCheck/><span><strong>Progressive login lockout</strong><small>Repeated unsuccessful attempts temporarily lock the account.</small></span></div></div></Card>}
    {section==='notifications' && <Card className="settings-card"><div className="section-heading"><div><span className="eyebrow">Team alerts</span><h2>Notifications</h2><p>Choose the operational events that should produce email alerts.</p></div></div><label className="toggle-row"><span><strong>Email notifications</strong><small>Account, quotation, and follow-up email messages.</small></span><input type="checkbox" checked={Boolean(values.emailNotifications)} onChange={event=>set('emailNotifications',event.target.checked)}/></label><label className="toggle-row"><span><strong>Approval notifications</strong><small>Notify reviewers when quotations need a decision.</small></span><input type="checkbox" checked={Boolean(values.approvalNotifications)} onChange={event=>set('approvalNotifications',event.target.checked)}/></label></Card>}
    {section==='data' && <Card className="settings-card"><div className="section-heading"><div><span className="eyebrow">Portability</span><h2>Data export</h2><p>Download an administrative JSON snapshot for controlled backup or migration.</p></div></div><Button tone="secondary" onClick={exportData}><Download/>Export accessible data</Button><div className="data-warning"><ShieldCheck/><span><strong>Protected operation</strong><small>Exports are recorded in security audit history. Store downloaded files securely.</small></span></div></Card>}
  </div></div></div>;
}
