import * as Dialog from '@radix-ui/react-dialog';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Check, ChevronDown, Filter, Search, Shield, SlidersHorizontal, UserCheck, UserRoundCog, UserX, X } from 'lucide-react';
import { useMemo, useState } from 'react';
import { api, jsonBody, pageResult } from '../lib/api';
import type { PageResult, User } from '../types';
import { fullName, shortDate, titleCase } from '../lib/format';
import { useAuth } from '../context/AuthContext';
import { useToast } from '../context/ToastContext';
import { Badge, Button, EmptyState, ErrorState, LoadingState, PageHeader, Pagination } from '../components/ui';

const permissionGroups: Record<string,{ key:string; label:string }[]> = {
  Catalog: [{key:'products_manage',label:'Add and edit products'},{key:'products_delete',label:'Delete products'},{key:'rates_view',label:'View rates'},{key:'rates_manage',label:'Change rates'}],
  Customers: [{key:'customers_view_all',label:'View all customers'},{key:'customers_manage_all',label:'Edit all customers'},{key:'customers_delete_own',label:'Delete own customers'},{key:'customers_delete_all',label:'Delete all customers'}],
  Quotations: [{key:'quotations_view_all',label:'View all quotations'},{key:'quotations_manage_all',label:'Edit all quotations'},{key:'quotations_delete_own',label:'Delete own quotations'},{key:'quotations_delete_all',label:'Delete all quotations'},{key:'quotations_send_all',label:'Send all quotations'},{key:'quotations_approve',label:'Approve quotations'}],
  Administration: [{key:'settings_manage',label:'Manage settings'},{key:'exports_manage',label:'Export data'},{key:'users_view_sensitive',label:'View sensitive profiles'},{key:'audit_view',label:'View audit history'}],
};
const idOf = (row: User) => row.id;

export default function Team() {
  const { user: me } = useAuth(); const { notify } = useToast(); const client = useQueryClient();
  const [page,setPage]=useState(1); const [search,setSearch]=useState(''); const [status,setStatus]=useState('all'); const [role,setRole]=useState('all'); const [accessUser,setAccessUser]=useState<User|null>(null); const [detailsUser,setDetailsUser]=useState<User|null>(null); const [permissions,setPermissions]=useState<Record<string,boolean>>({}); const [selected,setSelected]=useState<string[]>([]);
  const params=new URLSearchParams({page:String(page),limit:'20',...(search?{search}:{}),...(status!=='all'?{status}:{}),...(role!=='all'?{role}:{})});
  const query=useQuery({queryKey:['users',page,search,status,role],queryFn:()=>api<PageResult<User>|User[]>(`/users?${params}`)}); const data=query.data?pageResult(query.data):null;
  const counts=useMemo(()=>({pending:data?.items.filter(row=>row.status==='pending').length||0,active:data?.items.filter(row=>row.status==='active').length||0,suspended:data?.items.filter(row=>row.status==='suspended').length||0}),[data]);
  const update=useMutation({mutationFn:({id,body}:{id:string;body:unknown})=>api(`/users/${id}`,{method:'PATCH',...jsonBody(body)}),onSuccess:()=>{client.invalidateQueries({queryKey:['users']});notify('Team member updated','success');},onError:error=>notify(error.message,'error')});
  const approve=useMutation({mutationFn:({id,status}:{id:string;status:string})=>api(`/users/${id}/approval`,{method:'PATCH',...jsonBody({status})}),onSuccess:()=>{client.invalidateQueries({queryKey:['users']});notify('Registration reviewed','success');},onError:error=>notify(error.message,'error')});
  const saveAccess=useMutation({mutationFn:()=>api(`/users/${idOf(accessUser!)}/permissions`,{method:'PATCH',...jsonBody({permissions})}),onSuccess:()=>{client.invalidateQueries({queryKey:['users']});setAccessUser(null);notify('Custom access updated','success');},onError:error=>notify(error.message,'error')});
  async function loadDetails(row:User){try{setDetailsUser(await api<User>(`/users/${row.id}`));}catch(error){notify(error instanceof Error?error.message:'Unable to load details','error');}}
  function openAccess(row:User){setAccessUser(row);setPermissions({...row.effectivePermissions,...row.permissions});}
  async function bulkSuspend(){for(const id of selected) await api(`/users/${id}`,{method:'PATCH',...jsonBody({status:'suspended'})});setSelected([]);client.invalidateQueries({queryKey:['users']});notify('Selected accounts suspended','success');}
  return <div className="page"><PageHeader title="Team Access" description="Approve accounts, assign roles, and tailor access for every team member." actions={selected.length?<Button tone="danger" onClick={bulkSuspend}><UserX/>Suspend {selected.length}</Button>:undefined}/><div className="team-metrics"><button onClick={()=>setStatus('pending')}><span>{counts.pending}</span>Pending approval</button><button onClick={()=>setStatus('active')}><span>{counts.active}</span>Active accounts</button><button onClick={()=>setStatus('suspended')}><span>{counts.suspended}</span>Suspended</button></div><div className="toolbar"><div className="search-box"><Search/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search team members…"/></div><label className="filter-select"><Filter/><select value={role} onChange={event=>setRole(event.target.value)}><option value="all">All roles</option><option value="admin">Admin</option><option value="manager">Manager</option><option value="employee">Employee</option></select><ChevronDown/></label><label className="filter-select"><SlidersHorizontal/><select value={status} onChange={event=>setStatus(event.target.value)}><option value="all">All statuses</option><option value="pending">Pending</option><option value="active">Active</option><option value="suspended">Suspended</option><option value="rejected">Rejected</option></select><ChevronDown/></label></div>
    {query.isLoading?<LoadingState label="Loading team access"/>:query.error?<ErrorState error={query.error} retry={()=>query.refetch()}/>:!data?.items.length?<EmptyState title="No team members found" message="Change your filters to view another group."/>:<><div className="responsive-table team-table"><div className="table-head"><span>Team member</span><span>Role</span><span>Contact</span><span>Requested</span><span>Status</span><span>Actions</span></div>{data.items.map(row=><article className="table-row" key={row.id}><div className="customer-cell"><input type="checkbox" aria-label={`Select ${fullName(row)}`} disabled={row.role==='super_admin'||row.id===me?.id} checked={selected.includes(row.id)} onChange={event=>setSelected(current=>event.target.checked?[...current,row.id]:current.filter(id=>id!==row.id))}/><span className="avatar">{row.profilePicture?<img src={row.profilePicture} alt=""/>:row.firstName?.[0]}</span><span><strong>{fullName(row)}</strong><small>{row.designation||titleCase(row.role)}</small></span></div><div>{me?.role==='super_admin'&&row.role!=='super_admin'?<select className="select compact-select" value={row.role} onChange={event=>update.mutate({id:row.id,body:{role:event.target.value}})}><option value="admin">Admin</option><option value="manager">Manager</option><option value="employee">Employee</option></select>:<strong>{titleCase(row.role)}</strong>}{Object.keys(row.permissions||{}).length>0&&<Badge tone="warning">Custom access</Badge>}</div><div className="stack-cell"><span>{row.email}</span><small>{row.phone}</small></div><div><span>{shortDate(row.createdAt)}</span></div><div><Badge tone={row.status==='active'?'success':row.status==='pending'?'warning':'danger'}>{titleCase(row.status)}</Badge></div><div className="row-actions row-actions--labeled"><button onClick={()=>loadDetails(row)}><UserRoundCog/><span>Details</span></button>{me?.role==='super_admin'&&['manager','employee'].includes(row.role)&&<button className="accent" onClick={()=>openAccess(row)}><Shield/><span>Access</span></button>}{row.status==='pending'&&me?.role==='super_admin'?<><button className="success" onClick={()=>approve.mutate({id:row.id,status:'active'})}><UserCheck/><span>Approve</span></button><button className="danger" onClick={()=>approve.mutate({id:row.id,status:'rejected'})}><UserX/><span>Reject</span></button></>:row.role!=='super_admin'&&row.id!==me?.id?<button onClick={()=>update.mutate({id:row.id,body:{status:row.status==='suspended'?'active':'suspended'}})}>{row.status==='suspended'?<UserCheck/>:<UserX/>}<span>{row.status==='suspended'?'Reactivate':'Suspend'}</span></button>:null}</div></article>)}</div><Pagination page={data.meta.page} pages={data.meta.pages} onChange={setPage}/></>}
    <Dialog.Root open={Boolean(accessUser)} onOpenChange={open=>!open&&setAccessUser(null)}><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className="dialog dialog--permissions"><div className="dialog__header"><div><Dialog.Title>Access for {accessUser&&fullName(accessUser)}</Dialog.Title><Dialog.Description>Control operational capabilities without changing the user’s role.</Dialog.Description></div><Dialog.Close className="dialog__close"><X/></Dialog.Close></div><div className="permission-groups">{Object.entries(permissionGroups).map(([group,rows])=><section key={group}><h3>{group}</h3>{rows.map(item=><label key={item.key}><span><strong>{item.label}</strong><small>{item.key}</small></span><input type="checkbox" checked={Boolean(permissions[item.key])} onChange={event=>setPermissions(current=>({...current,[item.key]:event.target.checked}))}/></label>)}</section>)}</div><div className="dialog__actions"><Button tone="secondary" onClick={()=>setAccessUser(null)}>Cancel</Button><Button disabled={saveAccess.isPending} onClick={()=>saveAccess.mutate()}><Check/>Save access</Button></div></Dialog.Content></Dialog.Portal></Dialog.Root>
    <Dialog.Root open={Boolean(detailsUser)} onOpenChange={open=>!open&&setDetailsUser(null)}><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className="dialog dialog--form"><div className="dialog__header"><div><Dialog.Title>{detailsUser&&fullName(detailsUser)}</Dialog.Title><Dialog.Description>Sensitive profile information. Access is recorded.</Dialog.Description></div><Dialog.Close className="dialog__close"><X/></Dialog.Close></div>{detailsUser&&<div className="detail-grid">{Object.entries({Email:detailsUser.email,Phone:detailsUser.phone,Role:titleCase(detailsUser.role),Status:titleCase(detailsUser.status),Department:detailsUser.department||'—',Designation:detailsUser.designation||'—',City:detailsUser.city||'—',Address:detailsUser.address||'—','Last login':shortDate(detailsUser.lastLoginAt)}).map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>}</Dialog.Content></Dialog.Portal></Dialog.Root>
  </div>;
}
