// ============================================
// SKYLAND ENERGY — Seed Data
// Pre-populated from analyzed BOQ/Rates files
// ============================================
import { getDB, getAllProducts, setSetting } from './database.js';

const DEFAULT_PRODUCTS = [
  // ---- Solar Panels ----
  {
    name: 'Trina N-Type Bifacial Solar Panel',
    category: 'solar-panel',
    brand: 'Trina',
    model: 'Vertex N 725W',
    capacity: '725',
    capacityUnit: 'W',
    unit: 'piece',
    unitPrice: 27913,
    pricePerWatt: 38.50,
    image: '',
    specifications: {
      Technology: 'N-Type Bifacial',
      Warranty: '25 Years',
      Efficiency: '22.5%',
    },
  },
  {
    name: 'Canadian N-Type Bifacial Solar Panel',
    category: 'solar-panel',
    brand: 'Canadian Solar',
    model: 'HiKu7 CS7N 715W',
    capacity: '715',
    capacityUnit: 'W',
    unit: 'piece',
    unitPrice: 29673,
    pricePerWatt: 41.50,
    image: '',
    specifications: {
      Technology: 'N-Type Bifacial',
      Warranty: '25 Years',
    },
  },
  {
    name: 'Risen HJT Solar Panel',
    category: 'solar-panel',
    brand: 'Risen',
    model: 'HJT 740W',
    capacity: '740',
    capacityUnit: 'W',
    unit: 'piece',
    unitPrice: 31080,
    pricePerWatt: 42.00,
    image: '',
    specifications: {
      Technology: 'HJT (Heterojunction)',
      Warranty: '30 Years',
    },
  },
  {
    name: 'Longi Himo X10 Solar Panel',
    category: 'solar-panel',
    brand: 'Longi',
    model: 'Himo X10 645W',
    capacity: '645',
    capacityUnit: 'W',
    unit: 'piece',
    unitPrice: 26768,
    pricePerWatt: 41.50,
    image: '',
    specifications: {
      Technology: 'N-Type Bifacial',
      Warranty: '25 Years',
    },
  },
  {
    name: 'Jinko N-Type Bifacial Solar Panel',
    category: 'solar-panel',
    brand: 'Jinko',
    model: 'Tiger Neo 725W',
    capacity: '725',
    capacityUnit: 'W',
    unit: 'piece',
    unitPrice: 29725,
    pricePerWatt: 41.00,
    image: '',
    specifications: {
      Technology: 'N-Type Bifacial',
      Warranty: '25 Years',
    },
  },
  {
    name: 'JA N-Type Bifacial Solar Panel',
    category: 'solar-panel',
    brand: 'JA Solar',
    model: 'DeepBlue 4.0 Pro 585W',
    capacity: '585',
    capacityUnit: 'W',
    unit: 'piece',
    unitPrice: 24263,
    pricePerWatt: 41.50,
    image: '',
    specifications: {
      Technology: 'N-Type Bifacial',
      Warranty: '25 Years',
    },
  },

  // ---- On-Grid Inverters (Huawei) ----
  {
    name: 'Huawei On-Grid Inverter 10KTL',
    category: 'inverter',
    brand: 'Huawei',
    model: 'SUN2000-10KTL',
    capacity: '10',
    capacityUnit: 'kW',
    unit: 'piece',
    unitPrice: 250000,
    inverterType: 'ongrid',
    image: '',
    specifications: { Type: 'On-Grid', Phase: '3-Phase', Warranty: '10 Years' },
  },
  {
    name: 'Huawei On-Grid Inverter 15KTL',
    category: 'inverter',
    brand: 'Huawei',
    model: 'SUN2000-15KTL',
    capacity: '15',
    capacityUnit: 'kW',
    unit: 'piece',
    unitPrice: 310000,
    inverterType: 'ongrid',
    image: '',
    specifications: { Type: 'On-Grid', Phase: '3-Phase', Warranty: '10 Years' },
  },
  {
    name: 'Huawei On-Grid Inverter 20KTL',
    category: 'inverter',
    brand: 'Huawei',
    model: 'SUN2000-20KTL',
    capacity: '20',
    capacityUnit: 'kW',
    unit: 'piece',
    unitPrice: 330000,
    inverterType: 'ongrid',
    image: '',
    specifications: { Type: 'On-Grid', Phase: '3-Phase', Warranty: '10 Years' },
  },
  {
    name: 'Huawei On-Grid Inverter 30KTL',
    category: 'inverter',
    brand: 'Huawei',
    model: 'SUN2000-30KTL',
    capacity: '30',
    capacityUnit: 'kW',
    unit: 'piece',
    unitPrice: 560000,
    inverterType: 'ongrid',
    image: '',
    specifications: { Type: 'On-Grid', Phase: '3-Phase', Warranty: '10 Years' },
  },
  {
    name: 'Huawei On-Grid Inverter 50KTL',
    category: 'inverter',
    brand: 'Huawei',
    model: 'SUN2000-50KTL',
    capacity: '50',
    capacityUnit: 'kW',
    unit: 'piece',
    unitPrice: 560000,
    inverterType: 'ongrid',
    image: '',
    specifications: { Type: 'On-Grid', Phase: '3-Phase', Warranty: '10 Years' },
  },
  {
    name: 'Huawei On-Grid Inverter 115KTL',
    category: 'inverter',
    brand: 'Huawei',
    model: 'SUN2000-115KTL',
    capacity: '115',
    capacityUnit: 'kW',
    unit: 'piece',
    unitPrice: 1260000,
    inverterType: 'ongrid',
    image: '',
    specifications: { Type: 'On-Grid', Phase: '3-Phase', Warranty: '10 Years' },
  },

  // ---- On-Grid Inverters (GoodWe) ----
  {
    name: 'GoodWe On-Grid Inverter 15kW',
    category: 'inverter',
    brand: 'GoodWe',
    model: 'GW15KN-DT',
    capacity: '15',
    capacityUnit: 'kW',
    unit: 'piece',
    unitPrice: 210000,
    inverterType: 'ongrid',
    image: '',
    specifications: { Type: 'On-Grid', Phase: '3-Phase', Warranty: '10 Years' },
  },
  {
    name: 'GoodWe On-Grid Inverter 30kW',
    category: 'inverter',
    brand: 'GoodWe',
    model: 'GW30KN-DT',
    capacity: '30',
    capacityUnit: 'kW',
    unit: 'piece',
    unitPrice: 365000,
    inverterType: 'ongrid',
    image: '',
    specifications: { Type: 'On-Grid', Phase: '3-Phase', Warranty: '10 Years' },
  },
  {
    name: 'GoodWe On-Grid Inverter 50kW',
    category: 'inverter',
    brand: 'GoodWe',
    model: 'GW50KN-MT',
    capacity: '50',
    capacityUnit: 'kW',
    unit: 'piece',
    unitPrice: 475000,
    inverterType: 'ongrid',
    image: '',
    specifications: { Type: 'On-Grid', Phase: '3-Phase', Warranty: '10 Years' },
  },

  // ---- Hybrid Inverters (GoodWe) ----
  {
    name: 'GoodWe 1-Ph Hybrid Inverter 6kW',
    category: 'inverter',
    brand: 'GoodWe',
    model: 'GW6000-EH',
    capacity: '6',
    capacityUnit: 'kW',
    unit: 'piece',
    unitPrice: 215000,
    inverterType: 'hybrid',
    image: '',
    specifications: { Type: 'Hybrid', Phase: '1-Phase', Warranty: '10 Years' },
  },
  {
    name: 'GoodWe 3-Ph Hybrid Inverter 12kW',
    category: 'inverter',
    brand: 'GoodWe',
    model: 'GW12K-ET',
    capacity: '12',
    capacityUnit: 'kW',
    unit: 'piece',
    unitPrice: 500000,
    inverterType: 'hybrid',
    image: '',
    specifications: { Type: 'Hybrid', Phase: '3-Phase', Warranty: '10 Years' },
  },
  {
    name: 'GoodWe 3-Ph Hybrid Inverter 15kW',
    category: 'inverter',
    brand: 'GoodWe',
    model: 'GW15K-ET',
    capacity: '15',
    capacityUnit: 'kW',
    unit: 'piece',
    unitPrice: 600000,
    inverterType: 'hybrid',
    image: '',
    specifications: { Type: 'Hybrid', Phase: '3-Phase', Warranty: '10 Years' },
  },
  {
    name: 'GoodWe 3-Ph Hybrid Inverter 20kW',
    category: 'inverter',
    brand: 'GoodWe',
    model: 'GW20K-ET',
    capacity: '20',
    capacityUnit: 'kW',
    unit: 'piece',
    unitPrice: 795000,
    inverterType: 'hybrid',
    image: '',
    specifications: { Type: 'Hybrid', Phase: '3-Phase', Warranty: '10 Years' },
  },
  {
    name: 'GoodWe 3-Ph Hybrid Inverter 30kW',
    category: 'inverter',
    brand: 'GoodWe',
    model: 'GW30K-ET',
    capacity: '30',
    capacityUnit: 'kW',
    unit: 'piece',
    unitPrice: 1020000,
    inverterType: 'hybrid',
    image: '',
    specifications: { Type: 'Hybrid', Phase: '3-Phase', Warranty: '10 Years' },
  },
  {
    name: 'GoodWe 3-Ph Hybrid Inverter 50kW',
    category: 'inverter',
    brand: 'GoodWe',
    model: 'GW50K-ET',
    capacity: '50',
    capacityUnit: 'kW',
    unit: 'piece',
    unitPrice: 1420000,
    inverterType: 'hybrid',
    image: '',
    specifications: { Type: 'Hybrid', Phase: '3-Phase', Warranty: '10 Years' },
  },

  // ---- Batteries (GoodWe) ----
  {
    name: 'GoodWe Lithium Battery 5kWh',
    category: 'battery',
    brand: 'GoodWe',
    model: 'Lynx Home U 5.0',
    capacity: '5',
    capacityUnit: 'kWh',
    unit: 'piece',
    unitPrice: 265000,
    image: '',
    specifications: { Chemistry: 'LiFePO4', Warranty: '10 Years', Cycles: '6000+' },
  },
  {
    name: 'GoodWe Lithium Battery 14.3kWh',
    category: 'battery',
    brand: 'GoodWe',
    model: 'Lynx Home U 14.3',
    capacity: '14.3',
    capacityUnit: 'kWh',
    unit: 'piece',
    unitPrice: 700000,
    image: '',
    specifications: { Chemistry: 'LiFePO4', Warranty: '10 Years', Cycles: '6000+' },
  },

  // ---- Batteries (Soluna) ----
  {
    name: 'Soluna Lithium Battery 5kWh',
    category: 'battery',
    brand: 'Soluna',
    model: '5kWh IP65',
    capacity: '5',
    capacityUnit: 'kWh',
    unit: 'piece',
    unitPrice: 270000,
    image: '',
    specifications: { Chemistry: 'LiFePO4', Rating: 'IP65', Warranty: '10 Years' },
  },
  {
    name: 'Soluna Lithium Battery 16kWh',
    category: 'battery',
    brand: 'Soluna',
    model: '16kWh IP65',
    capacity: '16',
    capacityUnit: 'kWh',
    unit: 'piece',
    unitPrice: 685000,
    image: '',
    specifications: { Chemistry: 'LiFePO4', Rating: 'IP65', Warranty: '10 Years' },
  },
  {
    name: 'Soluna Lithium Battery 32kWh',
    category: 'battery',
    brand: 'Soluna',
    model: '32kWh IP65',
    capacity: '32',
    capacityUnit: 'kWh',
    unit: 'piece',
    unitPrice: 1365000,
    image: '',
    specifications: { Chemistry: 'LiFePO4', Rating: 'IP65', Warranty: '10 Years' },
  },

  // ---- Structures ----
  {
    name: 'Mounting Structure L-2 & L-1 GI',
    category: 'structure',
    brand: 'GI Standard',
    model: 'L-2 & L-1 (12 SWG)',
    capacity: '',
    capacityUnit: '',
    unit: 'set',
    unitPrice: 6600,
    image: '',
    specifications: { Material: 'Galvanized Iron', Gauge: '12 SWG', Type: 'L-2 & L-1' },
  },

  // ---- Accessories ----
  {
    name: 'DB Box & Breakers',
    category: 'accessory',
    brand: 'Chint / CNC',
    model: 'Standard',
    capacity: '',
    capacityUnit: '',
    unit: 'job',
    unitPrice: 28600,
    image: '',
    specifications: { Brand: 'Chint or CNC' },
  },
  {
    name: 'PVC Material & Accessories',
    category: 'accessory',
    brand: 'Popular / GM',
    model: 'Pipes, Ducts, Cable Ties',
    capacity: '',
    capacityUnit: '',
    unit: 'job',
    unitPrice: 21099,
    image: '',
    specifications: { Includes: 'PVC pipes, ducts, cable ties, accessories' },
  },
  {
    name: 'Lightning Arrester',
    category: 'accessory',
    brand: 'Standard',
    model: 'Lightning Protection',
    capacity: '',
    capacityUnit: '',
    unit: 'piece',
    unitPrice: 14500,
    image: '',
    specifications: {},
  },

  // ---- Cables ----
  {
    name: 'AC Cable (Copper)',
    category: 'cable',
    brand: 'Fast / Newage / GM',
    model: 'Copper AC Cable',
    capacity: '',
    capacityUnit: '',
    unit: 'job',
    unitPrice: 7150,
    image: '',
    specifications: { Material: 'Copper' },
  },
  {
    name: 'DC Cable (XLPO/XLPO)',
    category: 'cable',
    brand: 'Imported',
    model: '4mm-6mm XLPO/XLPO',
    capacity: '',
    capacityUnit: '',
    unit: 'job',
    unitPrice: 32500,
    image: '',
    specifications: { Size: '4mm to 6mm', Type: 'XLPO/XLPO Imported' },
  },
  {
    name: 'Earthing Cable',
    category: 'cable',
    brand: 'Fast / Newage / GM',
    model: 'Earthing Cable',
    capacity: '',
    capacityUnit: '',
    unit: 'job',
    unitPrice: 12402,
    image: '',
    specifications: {},
  },
];

// Standard BOQ Template (16 line items)
export const BOQ_TEMPLATE = [
  {
    name: 'Solar Panels Tier-1, 600W to 750W',
    description: 'N-Type Bifacial panels',
    category: 'solar-panel',
    unit: 'piece',
    quantity: 0,
    unitPrice: 0,
    isRequired: true,
  },
  {
    name: 'Inverter',
    description: 'On-Grid / Hybrid Inverter',
    category: 'inverter',
    unit: 'piece',
    quantity: 1,
    unitPrice: 0,
    isRequired: true,
  },
  {
    name: 'Mounting Structure Standard L-2 GI (12 SWG)',
    description: 'Galvanized Iron mounting structure',
    category: 'structure',
    unit: 'job',
    quantity: 1,
    unitPrice: 0,
    isRequired: true,
  },
  {
    name: 'DB Box and Breakers (Chint or CNC)',
    description: 'Distribution box and circuit breakers',
    category: 'accessory',
    unit: 'job',
    quantity: 1,
    unitPrice: 0,
    isRequired: true,
  },
  {
    name: 'PVC pipes, ducts, cable ties, other accessories',
    description: 'Popular or GM brand',
    category: 'accessory',
    unit: 'job',
    quantity: 1,
    unitPrice: 0,
    isRequired: true,
  },
  {
    name: 'DC cables (XLPO/XLPO 4mm to 6mm Imported), AC cable for Inverters (copper) and earthing cables',
    description: 'Fast, Newage or GM brand',
    category: 'cable',
    unit: 'job',
    quantity: 1,
    unitPrice: 0,
    isRequired: true,
  },
  {
    name: 'Civil works (concrete blocks)',
    description: 'Foundation and civil construction',
    category: 'service',
    unit: 'job',
    quantity: 1,
    unitPrice: 0,
    isRequired: true,
  },
  {
    name: 'Earthing & boring',
    description: 'Grounding system installation',
    category: 'service',
    unit: 'piece',
    quantity: 3,
    unitPrice: 20000,
    isRequired: true,
  },
  {
    name: 'Lightning arrester',
    description: 'Lightning protection system',
    category: 'accessory',
    unit: 'piece',
    quantity: 1,
    unitPrice: 14500,
    isRequired: true,
  },
  {
    name: 'Engineering, designing, supervision, testing & commissioning',
    description: 'Professional engineering services',
    category: 'service',
    unit: 'job',
    quantity: 1,
    unitPrice: 0,
    isRequired: true,
  },
  {
    name: 'Installation, electrification & wiring',
    description: 'Electrical & Mechanical Labor',
    category: 'service',
    unit: 'job',
    quantity: 1,
    unitPrice: 0,
    isRequired: true,
  },
  {
    name: 'Transportation and travelling',
    description: 'Logistics and transportation',
    category: 'service',
    unit: 'job',
    quantity: 1,
    unitPrice: 0,
    isRequired: true,
  },
  {
    name: 'One year free of cost after sales services',
    description: 'Maintenance and support',
    category: 'service',
    unit: 'job',
    quantity: 1,
    unitPrice: 0,
    isRequired: false,
  },
  {
    name: 'Net Metering',
    description: 'Net metering facility setup (optional)',
    category: 'service',
    unit: 'job',
    quantity: 1,
    unitPrice: 0,
    isRequired: false,
    isOptional: true,
  },
];

export const DEFAULT_TERMS = [
  'Prices are valid for 5 days only from the date of quotation.',
  'Advance amount @ 20% and remaining 80% amount will be received during installation.',
  'System will be delivered and installed in 5 to 7 working days approx. subject to timely payments of funds.',
  'Order will be confirmed upon receiving of advance payment.',
  'Above prices are exclusive of all taxes, if applicable withholding tax, sales tax or any other taxes, same amount will be added in above mentioned prices.',
  'The offer is based on the current exchange rate of US Dollar @ 1 USD = 285 PKR, any fluctuation can affect the quoted price.',
  'Imported items delivery will be subject to the availability and Govt policies.',
  'AC cable from inverters location to main DB (LT) will be provided by the client.',
  'Net metering facility is not included in this quotation.',
  'Zero export device and PV Genset controller scope is not included in above prices and will be charged separately if required.',
  'The client shall arrange and maintain a comprehensive insurance policy covering loss, damage or delays resulting from any kind of Force Majeures and for any unforeseen events.',
  'Client shall arrange and provide a stable internet (Wi-Fi) connection for remote monitoring of the installed solar system.',
];

export const DEFAULT_SETTINGS = {
  companyName: 'Skyland Energy',
  companyAddress: 'Lahore, Pakistan',
  companyPhone: '',
  companyEmail: '',
  validityDays: 5,
  advancePercent: 20,
  exchangeRate: 285,
  defaultTerms: DEFAULT_TERMS,
};

export async function seedDatabase() {
  const db = await getDB();
  const products = await getAllProducts();

  // Only seed if database is empty
  if (products.length > 0) return;

  const tx = db.transaction('products', 'readwrite');
  for (const product of DEFAULT_PRODUCTS) {
    await tx.store.add({
      ...product,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    });
  }
  await tx.done;

  // Seed settings
  for (const [key, value] of Object.entries(DEFAULT_SETTINGS)) {
    await setSetting(key, value);
  }

  console.log('✅ Database seeded with', DEFAULT_PRODUCTS.length, 'products');
}
